
auth_enabled: false


server:
  http_listen_port: 3100 
  log_level: info 

limits_config:
  volume_enabled: true
  allow_structured_metadata: true
  max_structured_metadata_size: 64KB
  max_structured_metadata_entries_count: 128

common:
  instance_addr:
    127.0.0.1 
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks 
      rules_directory: /loki/rules 
  replication_factor:
    1 
  ring:
    kvstore:
      store: inmemory

schema_config:
  # Only one config is specified here.
  configs:
    - from: 2020-10-24 # When the schema applies from.
      store: tsdb # Where the schema is stored, in this case using the TSDB store.
      object_store: filesystem # As configured in the common block above, the object store is the local filesystem.
      schema: v13 # Specify the schema version to use, in this case the latest version (v13).
      # The index configuration block is used to configure how indexing tables are created and stored. Index tables
      # are the directory that allows Loki to determine which chunks to read when querying for logs.
      index:
        prefix: index_ # Prefix for all index tables.
        period: 24h # The period for which each index table covers. In this case, 24 hours.

# The ruler configuration block to configure the ruler (for recording rules and alerts) in Loki.
ruler:
  alertmanager_url:
    http://localhost:9093 # The URL of the Alertmanager to send alerts to. Again, this is a single
    # binary instance running on the same host, so it's localhost.
# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false
